#' @importClassesFrom tidytree treedata
setClass("fbdrange", contains = "treedata")
setGeneric("as.fbdrange", function(data, ...) standardGeneric("as.fbdrange"))

#' Title
#'
#' @param data 
#'
#' @return
#' @export
#'
#' @examples
fbdrange = function(data) {
  if(inherits(data, "treedata")) return(as.fbdrange(data))
  
  #TODO checks that fbd range object contains elements "range" and "orientation" as part of data
  
}

#' @importFrom methods new
as.fbdrange.treedata = function(data, ...) {
  if(is.null(data@data$range) || is.null(data@data$orientation)) stop("Fbdrange objects require range and orientation data")
  fbd = new("fbdrange", data)
}
setMethod("as.fbdrange", "treedata", as.fbdrange.treedata)

as.fbdrange.default = function(data, ...) {
  fbdrange(data, ...)
}
setMethod("as.fbdrange", "ANY", as.fbdrange.default)

#' Import fbdrange object from file
#'
#' @param input_file path to a tree file in Nexus format containing range and orientation metadata for the trees (for instance, a file generated by the BEAST2 package TODO)
#'
#' @return an fbdrange object
#' @export
#'
#' @examples
get_fbdrange_from_file = function(input_file) {
  if (!requireNamespace("treeio", quietly = TRUE)) {
    stop("Package treeio is needed for this function to work. Please install it.", call. = FALSE)
  }
  
  tree <- treeio::read.beast(input_file)
  as.fbdrange(tree)
}
